name: CI/CD

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Build package & test
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install -e .
          py.test -v
